cleanNamespace: true
bucket: {}
packages:
  - name: default
    actions:
      - name: "hello"
        runtime: 'go:default'
        web: false
    shared: true
    clean: true
    annotations:
      "provide-api-key": ""
      "require-whisk-auth": ""
