cleanNamespace: true
bucket: {}
packages:
  - name: default
    actions:
      - name: "hello"
        runtime: 'go:default'
        web: false
        webSecure: true
        clean: true
        annotations:
          "require-whisk-auth": ""
          "provide-api-key": ""
    shared: false
    clean: false
    annotations:
      "other_annotation": "yolo"
