packages:
  - name: default
    actions:
      - name: "hello"
        runtime: 'go:default'
        web: false
        environment:
          DB_HOSTNAME: "${DB_HOSTNAME}"
          DB_DATABASE: "${DB_DATABASE}"
          DB_PASSWORD: "${DB_PASSWORD}"
          DB_USERNAME: "${DB_USERNAME}"
          DB_PORT: "${DB_PORT}"
